# =============================================================================
# ComfyUI Makefile
# Generated by makefile-generator skill
# =============================================================================

# ---- Configuration ----------------------------------------------------------

PYTHON       ?= python
SERVICE_NAME ?= comfyui
PROJECT_NAME := ComfyUI

# ---- Colors ----------------------------------------------------------------

BLUE   := \033[1;34m
GREEN  := \033[1;32m
YELLOW := \033[1;33m
RESET  := \033[0m

# ---- Prerequisite helpers ---------------------------------------------------

# Ensure uv is available
.PHONY: _ensure-uv
_ensure-uv:
	@which uv > /dev/null 2>&1 || (echo "$(YELLOW)uv not found. Installing...$(RESET)" && curl -LsSf https://astral.sh/uv/install.sh | sh)

# Ensure python venv is active
.PHONY: _ensure-venv
_ensure-venv:
	@test -n "$$VIRTUAL_ENV" || (echo "$(YELLOW)No virtual environment active. Activate with: source .venv/bin/activate$(RESET)" && exit 1)

# =============================================================================
# Primary targets
# =============================================================================

.PHONY: help
help: ## Show this help
	@echo ""
	@echo "$(BLUE)$(PROJECT_NAME) — available targets:$(RESET)"
	@echo ""
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  $(GREEN)%-18s$(RESET) %s\n", $$1, $$2}'
	@echo ""

# ---- Install ----------------------------------------------------------------

.PHONY: install
install: _ensure-uv ## Install dependencies
	uv pip install -r requirements.txt
	@if [ -f manager_requirements.txt ]; then uv pip install -r manager_requirements.txt; fi
	@if [ -f tests-unit/requirements.txt ]; then uv pip install -r tests-unit/requirements.txt; fi

.PHONY: full_install
full_install: clean install build ## Clean install + build from scratch

.PHONY: update
update: ## git pull + install + build
	git pull
	$(MAKE) install
	$(MAKE) build

.PHONY: full_update
full_update: clean ## Clean + update (full rebuild)
	git pull
	$(MAKE) install
	$(MAKE) build

# ---- Build ------------------------------------------------------------------

.PHONY: build
build: ## Build frontend package (pip install comfyui deps)
	uv pip install comfyui-frontend-package comfyui-workflow-templates comfyui-embedded-docs

# ---- Run --------------------------------------------------------------------

.PHONY: dev
dev: _ensure-venv ## Run in development mode (with auto-reload)
	$(PYTHON) main.py --listen 0.0.0.0 --port 8188 --verbose

.PHONY: run
run: build _ensure-venv ## Run in production mode
	$(PYTHON) main.py --listen 0.0.0.0 --port 8188

# ---- Service management (systemd) -------------------------------------------

.PHONY: start
start: ## Start the systemd service
	sudo systemctl start $(SERVICE_NAME)

.PHONY: stop
stop: ## Stop the systemd service
	sudo systemctl stop $(SERVICE_NAME)

.PHONY: restart
restart: build ## Build + restart the systemd service
	sudo systemctl restart $(SERVICE_NAME)

.PHONY: status
status: ## Show systemd service status
	sudo systemctl status $(SERVICE_NAME) --no-pager

.PHONY: logs
logs: ## Tail systemd service logs
	journalctl -u $(SERVICE_NAME) -f

# ---- Test -------------------------------------------------------------------

.PHONY: test
test: _ensure-venv ## Run all tests (unit + integration)
	$(PYTHON) -m pytest tests-unit tests -v

.PHONY: test-unit
test-unit: _ensure-venv ## Run unit tests only
	$(PYTHON) -m pytest tests-unit -v

.PHONY: test-integration
test-integration: _ensure-venv ## Run integration tests only
	$(PYTHON) -m pytest tests -v

# ---- Lint & Format ----------------------------------------------------------

.PHONY: lint
lint: ## Run linter (ruff check)
	$(PYTHON) -m ruff check .

.PHONY: format
format: ## Auto-format code (ruff fix)
	$(PYTHON) -m ruff check --fix .
	$(PYTHON) -m ruff format .

.PHONY: format-check
format-check: ## Check formatting without changes
	$(PYTHON) -m ruff format --check .

# ---- Clean ------------------------------------------------------------------

.PHONY: clean
clean: ## Remove build artifacts and caches
	find . -type d -name __pycache__ -not -path './.venv/*' -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name '*.pyc' -not -path './.venv/*' -delete 2>/dev/null || true
	find . -type d -name '*.egg-info' -not -path './.venv/*' -exec rm -rf {} + 2>/dev/null || true
	rm -rf .pytest_cache .ruff_cache
